"""add ips_municipio table

Revision ID: 68bbe475530f
Revises: a06cfa9f29a7
Create Date: 2026-05-06 09:13:26.250938

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '68bbe475530f'
down_revision = 'a06cfa9f29a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ips_municipio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipio_id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('area_km2', sa.Float(), nullable=True),
    sa.Column('populacao', sa.Integer(), nullable=True),
    sa.Column('pib_per_capita', sa.Float(), nullable=True),
    sa.Column('ips_geral', sa.Float(), nullable=True),
    sa.Column('necessidades_humanas_basicas', sa.Float(), nullable=True),
    sa.Column('fundamentos_bem_estar', sa.Float(), nullable=True),
    sa.Column('oportunidades', sa.Float(), nullable=True),
    sa.Column('nutricao_cuidados_medicos', sa.Float(), nullable=True),
    sa.Column('agua_saneamento', sa.Float(), nullable=True),
    sa.Column('moradia', sa.Float(), nullable=True),
    sa.Column('seguranca_pessoal', sa.Float(), nullable=True),
    sa.Column('acesso_conhecimento_basico', sa.Float(), nullable=True),
    sa.Column('acesso_informacao_comunicacao', sa.Float(), nullable=True),
    sa.Column('saude_bem_estar', sa.Float(), nullable=True),
    sa.Column('qualidade_meio_ambiente', sa.Float(), nullable=True),
    sa.Column('direitos_individuais', sa.Float(), nullable=True),
    sa.Column('liberdades_individuais', sa.Float(), nullable=True),
    sa.Column('inclusao_social', sa.Float(), nullable=True),
    sa.Column('acesso_educacao_superior', sa.Float(), nullable=True),
    sa.Column('cobertura_vacinal_poliomielite', sa.Float(), nullable=True),
    sa.Column('hospitalizacoes_csa', sa.Float(), nullable=True),
    sa.Column('mortalidade_ajustada_csa', sa.Float(), nullable=True),
    sa.Column('mortalidade_infantil_5_anos', sa.Float(), nullable=True),
    sa.Column('subnutricao', sa.Float(), nullable=True),
    sa.Column('abastecimento_agua_rede', sa.Float(), nullable=True),
    sa.Column('esgotamento_sanitario_adequado', sa.Float(), nullable=True),
    sa.Column('indice_abastecimento_agua', sa.Float(), nullable=True),
    sa.Column('indice_perdas_agua', sa.Float(), nullable=True),
    sa.Column('domicilios_coleta_residuos', sa.Float(), nullable=True),
    sa.Column('domicilios_iluminacao_eletrica', sa.Float(), nullable=True),
    sa.Column('domicilios_paredes_adequadas', sa.Float(), nullable=True),
    sa.Column('domicilios_piso_adequado', sa.Float(), nullable=True),
    sa.Column('assassinatos_jovens', sa.Float(), nullable=True),
    sa.Column('assassinatos_mulheres', sa.Float(), nullable=True),
    sa.Column('homicidios', sa.Float(), nullable=True),
    sa.Column('mortes_acidente_transporte', sa.Float(), nullable=True),
    sa.Column('abandono_ensino_fundamental', sa.Float(), nullable=True),
    sa.Column('abandono_ensino_medio', sa.Float(), nullable=True),
    sa.Column('evasao_ensino_medio', sa.Float(), nullable=True),
    sa.Column('distorcao_idade_serie', sa.Float(), nullable=True),
    sa.Column('ideb_ensino_fundamental', sa.Float(), nullable=True),
    sa.Column('reprovacao_escolar_medio', sa.Float(), nullable=True),
    sa.Column('cobertura_internet_movel', sa.Float(), nullable=True),
    sa.Column('densidade_internet_banda_larga', sa.Float(), nullable=True),
    sa.Column('densidade_telefonia_movel', sa.Float(), nullable=True),
    sa.Column('qualidade_internet_movel', sa.Float(), nullable=True),
    sa.Column('consumo_alimentos_ultraprocessados', sa.Float(), nullable=True),
    sa.Column('expectativa_vida', sa.Float(), nullable=True),
    sa.Column('mortalidade_15_50_anos', sa.Float(), nullable=True),
    sa.Column('mortalidade_dcnt', sa.Float(), nullable=True),
    sa.Column('obesidade', sa.Float(), nullable=True),
    sa.Column('suicidios', sa.Float(), nullable=True),
    sa.Column('areas_verdes_urbanas', sa.Float(), nullable=True),
    sa.Column('emissoes_co2_habitante', sa.Float(), nullable=True),
    sa.Column('focos_calor', sa.Float(), nullable=True),
    sa.Column('ivcm', sa.Float(), nullable=True),
    sa.Column('supressao_vegetacao', sa.Float(), nullable=True),
    sa.Column('acesso_prog_direitos_humanos', sa.Float(), nullable=True),
    sa.Column('acoes_direitos_minorias', sa.Float(), nullable=True),
    sa.Column('atendimento_demanda_justica', sa.Float(), nullable=True),
    sa.Column('resposta_processos_previdenciarios', sa.Float(), nullable=True),
    sa.Column('resposta_processos_familiares', sa.Float(), nullable=True),
    sa.Column('taxa_congestionamento_processos', sa.Float(), nullable=True),
    sa.Column('acesso_cultura_lazer_esporte', sa.Float(), nullable=True),
    sa.Column('gravidez_adolescencia', sa.Float(), nullable=True),
    sa.Column('ivcad', sa.Float(), nullable=True),
    sa.Column('pracas_parques_urbanas', sa.Float(), nullable=True),
    sa.Column('familias_situacao_rua', sa.Float(), nullable=True),
    sa.Column('paridade_genero_camara', sa.Float(), nullable=True),
    sa.Column('paridade_negros_camara', sa.Float(), nullable=True),
    sa.Column('violencia_indigenas', sa.Float(), nullable=True),
    sa.Column('violencia_mulheres', sa.Float(), nullable=True),
    sa.Column('violencia_negros', sa.Float(), nullable=True),
    sa.Column('empregados_ensino_superior', sa.Float(), nullable=True),
    sa.Column('mulheres_empregadas_ensino_superior', sa.Float(), nullable=True),
    sa.Column('nota_mediana_enem', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('municipio_id', 'ano', name='uq_ips_municipio_ano')
    )
    op.create_index(op.f('ix_ips_municipio_ano'), 'ips_municipio', ['ano'], unique=False)
    op.create_index(op.f('ix_ips_municipio_id'), 'ips_municipio', ['id'], unique=False)
    op.create_index(op.f('ix_ips_municipio_municipio_id'), 'ips_municipio', ['municipio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ips_municipio_municipio_id'), table_name='ips_municipio')
    op.drop_index(op.f('ix_ips_municipio_id'), table_name='ips_municipio')
    op.drop_index(op.f('ix_ips_municipio_ano'), table_name='ips_municipio')
    op.drop_table('ips_municipio')
    # ### end Alembic commands ###
