"""add desenvolvimento_economico tables

Revision ID: a06cfa9f29a7
Revises: 0020_projeto_acervo
Create Date: 2026-05-04 16:40:23.012666

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a06cfa9f29a7'
down_revision = '0020_projeto_acervo'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('captacao_recurso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipio_id', sa.Integer(), nullable=False),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('entidade_origem', sa.String(length=200), nullable=True),
    sa.Column('valor_estimado', sa.Float(), nullable=True),
    sa.Column('prazo', sa.Date(), nullable=True),
    sa.Column('estagio', sa.String(length=30), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['criado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_captacao_recurso_id'), 'captacao_recurso', ['id'], unique=False)
    op.create_index(op.f('ix_captacao_recurso_municipio_id'), 'captacao_recurso', ['municipio_id'], unique=False)
    op.create_table('empresa_retencao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipio_id', sa.Integer(), nullable=False),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('setor', sa.String(length=100), nullable=True),
    sa.Column('num_empregos', sa.Integer(), nullable=True),
    sa.Column('status_risco', sa.String(length=10), nullable=False),
    sa.Column('potencial_expansao', sa.String(length=10), nullable=False),
    sa.Column('responsavel', sa.String(length=150), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['criado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresa_retencao_id'), 'empresa_retencao', ['id'], unique=False)
    op.create_index(op.f('ix_empresa_retencao_municipio_id'), 'empresa_retencao', ['municipio_id'], unique=False)
    op.create_table('investimento_funil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipio_id', sa.Integer(), nullable=False),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('empresa_nome', sa.String(length=200), nullable=False),
    sa.Column('setor', sa.String(length=100), nullable=True),
    sa.Column('valor_estimado', sa.Float(), nullable=True),
    sa.Column('estagio', sa.String(length=30), nullable=False),
    sa.Column('responsavel', sa.String(length=150), nullable=True),
    sa.Column('proxima_acao', sa.Text(), nullable=True),
    sa.Column('proxima_acao_data', sa.Date(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['criado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investimento_funil_id'), 'investimento_funil', ['id'], unique=False)
    op.create_index(op.f('ix_investimento_funil_municipio_id'), 'investimento_funil', ['municipio_id'], unique=False)
    op.create_table('premiacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipio_id', sa.Integer(), nullable=False),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('entidade', sa.String(length=200), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('prazo', sa.Date(), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['criado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_premiacao_id'), 'premiacao', ['id'], unique=False)
    op.create_index(op.f('ix_premiacao_municipio_id'), 'premiacao', ['municipio_id'], unique=False)
    op.create_table('escrita_projeto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipio_id', sa.Integer(), nullable=False),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('oportunidade_captacao_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('estagio', sa.String(length=20), nullable=False),
    sa.Column('resultado', sa.String(length=20), nullable=True),
    sa.Column('responsavel', sa.String(length=150), nullable=True),
    sa.Column('prazo', sa.Date(), nullable=True),
    sa.Column('valor_pleiteado', sa.Float(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['criado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipios.id'], ),
    sa.ForeignKeyConstraint(['oportunidade_captacao_id'], ['captacao_recurso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escrita_projeto_id'), 'escrita_projeto', ['id'], unique=False)
    op.create_index(op.f('ix_escrita_projeto_municipio_id'), 'escrita_projeto', ['municipio_id'], unique=False)
    op.create_index(op.f('ix_escrita_projeto_oportunidade_captacao_id'), 'escrita_projeto', ['oportunidade_captacao_id'], unique=False)
    op.create_table('visita_retencao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('municipio_id', sa.Integer(), nullable=False),
    sa.Column('data_visita', sa.Date(), nullable=False),
    sa.Column('responsavel', sa.String(length=150), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('foto_base64', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa_retencao.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visita_retencao_empresa_id'), 'visita_retencao', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_visita_retencao_id'), 'visita_retencao', ['id'], unique=False)
    op.create_index(op.f('ix_visita_retencao_municipio_id'), 'visita_retencao', ['municipio_id'], unique=False)
    op.alter_column('arrecadacao_mensal', 'nome_mes',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('arrecadacao_mensal', 'data_base',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('arrecadacao_mensal', 'valor_icms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('arrecadacao_mensal', 'valor_ipva',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('arrecadacao_mensal', 'valor_ipi',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('arrecadacao_mensal', 'valor_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.create_index(op.f('ix_arrecadacao_mensal_ano'), 'arrecadacao_mensal', ['ano'], unique=False)
    op.create_index(op.f('ix_arrecadacao_mensal_id'), 'arrecadacao_mensal', ['id'], unique=False)
    op.create_index(op.f('ix_arrecadacao_mensal_mes'), 'arrecadacao_mensal', ['mes'], unique=False)
    op.create_index(op.f('ix_arrecadacao_mensal_municipio_id'), 'arrecadacao_mensal', ['municipio_id'], unique=False)
    op.drop_index(op.f('ix_bf_ano'), table_name='bolsa_familia_resumo')
    op.drop_index(op.f('ix_bf_mes'), table_name='bolsa_familia_resumo')
    op.drop_index(op.f('ix_bf_municipio_id'), table_name='bolsa_familia_resumo')
    op.create_index(op.f('ix_bolsa_familia_resumo_ano'), 'bolsa_familia_resumo', ['ano'], unique=False)
    op.create_index(op.f('ix_bolsa_familia_resumo_id'), 'bolsa_familia_resumo', ['id'], unique=False)
    op.create_index(op.f('ix_bolsa_familia_resumo_mes'), 'bolsa_familia_resumo', ['mes'], unique=False)
    op.create_index(op.f('ix_bolsa_familia_resumo_municipio_id'), 'bolsa_familia_resumo', ['municipio_id'], unique=False)
    op.drop_index(op.f('ix_caged_ano'), table_name='caged_movimentacao')
    op.drop_index(op.f('ix_caged_mes'), table_name='caged_movimentacao')
    op.drop_index(op.f('ix_caged_municipio_id'), table_name='caged_movimentacao')
    op.create_index(op.f('ix_caged_movimentacao_ano'), 'caged_movimentacao', ['ano'], unique=False)
    op.create_index(op.f('ix_caged_movimentacao_id'), 'caged_movimentacao', ['id'], unique=False)
    op.create_index(op.f('ix_caged_movimentacao_mes'), 'caged_movimentacao', ['mes'], unique=False)
    op.create_index(op.f('ix_caged_movimentacao_municipio_id'), 'caged_movimentacao', ['municipio_id'], unique=False)
    op.drop_index(op.f('ix_caged_cnae_ano'), table_name='caged_por_cnae')
    op.drop_index(op.f('ix_caged_cnae_mes'), table_name='caged_por_cnae')
    op.drop_index(op.f('ix_caged_cnae_municipio_id'), table_name='caged_por_cnae')
    op.create_index(op.f('ix_caged_por_cnae_ano'), 'caged_por_cnae', ['ano'], unique=False)
    op.create_index(op.f('ix_caged_por_cnae_id'), 'caged_por_cnae', ['id'], unique=False)
    op.create_index(op.f('ix_caged_por_cnae_mes'), 'caged_por_cnae', ['mes'], unique=False)
    op.create_index(op.f('ix_caged_por_cnae_municipio_id'), 'caged_por_cnae', ['municipio_id'], unique=False)
    op.drop_index(op.f('ix_caged_raca_ano'), table_name='caged_por_raca')
    op.drop_index(op.f('ix_caged_raca_mes'), table_name='caged_por_raca')
    op.drop_index(op.f('ix_caged_raca_municipio_id'), table_name='caged_por_raca')
    op.create_index(op.f('ix_caged_por_raca_ano'), 'caged_por_raca', ['ano'], unique=False)
    op.create_index(op.f('ix_caged_por_raca_id'), 'caged_por_raca', ['id'], unique=False)
    op.create_index(op.f('ix_caged_por_raca_mes'), 'caged_por_raca', ['mes'], unique=False)
    op.create_index(op.f('ix_caged_por_raca_municipio_id'), 'caged_por_raca', ['municipio_id'], unique=False)
    op.drop_index(op.f('ix_caged_sexo_ano'), table_name='caged_por_sexo')
    op.drop_index(op.f('ix_caged_sexo_mes'), table_name='caged_por_sexo')
    op.drop_index(op.f('ix_caged_sexo_municipio_id'), table_name='caged_por_sexo')
    op.create_index(op.f('ix_caged_por_sexo_ano'), 'caged_por_sexo', ['ano'], unique=False)
    op.create_index(op.f('ix_caged_por_sexo_id'), 'caged_por_sexo', ['id'], unique=False)
    op.create_index(op.f('ix_caged_por_sexo_mes'), 'caged_por_sexo', ['mes'], unique=False)
    op.create_index(op.f('ix_caged_por_sexo_municipio_id'), 'caged_por_sexo', ['municipio_id'], unique=False)
    op.create_index(op.f('ix_caged_salario_id'), 'caged_salario', ['id'], unique=False)
    op.drop_index(op.f('ix_comex_ano'), table_name='comex_mensal')
    op.drop_index(op.f('ix_comex_mes'), table_name='comex_mensal')
    op.drop_index(op.f('ix_comex_municipio_id'), table_name='comex_mensal')
    op.drop_index(op.f('ix_comex_tipo_op'), table_name='comex_mensal')
    op.create_index(op.f('ix_comex_mensal_ano'), 'comex_mensal', ['ano'], unique=False)
    op.create_index(op.f('ix_comex_mensal_id'), 'comex_mensal', ['id'], unique=False)
    op.create_index(op.f('ix_comex_mensal_mes'), 'comex_mensal', ['mes'], unique=False)
    op.create_index(op.f('ix_comex_mensal_municipio_id'), 'comex_mensal', ['municipio_id'], unique=False)
    op.create_index(op.f('ix_comex_mensal_tipo_operacao'), 'comex_mensal', ['tipo_operacao'], unique=False)
    op.drop_index(op.f('ix_comex_pais_ano'), table_name='comex_por_pais')
    op.drop_index(op.f('ix_comex_pais_municipio_id'), table_name='comex_por_pais')
    op.drop_index(op.f('ix_comex_pais_tipo_op'), table_name='comex_por_pais')
    op.create_index(op.f('ix_comex_por_pais_ano'), 'comex_por_pais', ['ano'], unique=False)
    op.create_index(op.f('ix_comex_por_pais_id'), 'comex_por_pais', ['id'], unique=False)
    op.create_index(op.f('ix_comex_por_pais_municipio_id'), 'comex_por_pais', ['municipio_id'], unique=False)
    op.create_index(op.f('ix_comex_por_pais_tipo_operacao'), 'comex_por_pais', ['tipo_operacao'], unique=False)
    op.drop_index(op.f('ix_comex_prod_ano'), table_name='comex_por_produto')
    op.drop_index(op.f('ix_comex_prod_municipio_id'), table_name='comex_por_produto')
    op.drop_index(op.f('ix_comex_prod_tipo_op'), table_name='comex_por_produto')
    op.create_index(op.f('ix_comex_por_produto_ano'), 'comex_por_produto', ['ano'], unique=False)
    op.create_index(op.f('ix_comex_por_produto_id'), 'comex_por_produto', ['id'], unique=False)
    op.create_index(op.f('ix_comex_por_produto_municipio_id'), 'comex_por_produto', ['municipio_id'], unique=False)
    op.create_index(op.f('ix_comex_por_produto_tipo_operacao'), 'comex_por_produto', ['tipo_operacao'], unique=False)
    op.alter_column('dataset_info', 'atualizado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_empresas_id'), 'empresas', ['id'], unique=False)
    op.drop_index(op.f('ix_estban_data_ref'), table_name='estban_mensal')
    op.drop_index(op.f('ix_estban_municipio_id'), table_name='estban_mensal')
    op.create_index(op.f('ix_estban_mensal_data_referencia'), 'estban_mensal', ['data_referencia'], unique=False)
    op.create_index(op.f('ix_estban_mensal_id'), 'estban_mensal', ['id'], unique=False)
    op.create_index(op.f('ix_estban_mensal_municipio_id'), 'estban_mensal', ['municipio_id'], unique=False)
    op.drop_index(op.f('ix_estban_inst_data_ref'), table_name='estban_por_instituicao')
    op.drop_index(op.f('ix_estban_inst_municipio_id'), table_name='estban_por_instituicao')
    op.drop_index(op.f('ix_estban_inst_nome'), table_name='estban_por_instituicao')
    op.create_index(op.f('ix_estban_por_instituicao_data_referencia'), 'estban_por_instituicao', ['data_referencia'], unique=False)
    op.create_index(op.f('ix_estban_por_instituicao_id'), 'estban_por_instituicao', ['id'], unique=False)
    op.create_index(op.f('ix_estban_por_instituicao_municipio_id'), 'estban_por_instituicao', ['municipio_id'], unique=False)
    op.create_index(op.f('ix_estban_por_instituicao_nome_instituicao'), 'estban_por_instituicao', ['nome_instituicao'], unique=False)
    op.alter_column('eventos_municipio', 'criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('indicadores_internos', 'criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('insights_ia', 'gerado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_insights_ia_id'), 'insights_ia', ['id'], unique=False)
    op.drop_index(op.f('ix_inss_ano'), table_name='inss_anual')
    op.drop_index(op.f('ix_inss_categoria'), table_name='inss_anual')
    op.drop_index(op.f('ix_inss_municipio_id'), table_name='inss_anual')
    op.create_index(op.f('ix_inss_anual_ano'), 'inss_anual', ['ano'], unique=False)
    op.create_index(op.f('ix_inss_anual_categoria'), 'inss_anual', ['categoria'], unique=False)
    op.create_index(op.f('ix_inss_anual_id'), 'inss_anual', ['id'], unique=False)
    op.create_index(op.f('ix_inss_anual_municipio_id'), 'inss_anual', ['municipio_id'], unique=False)
    op.create_index(op.f('ix_marcos_mandato_id'), 'marcos_mandato', ['id'], unique=False)
    op.create_index(op.f('ix_municipios_id'), 'municipios', ['id'], unique=False)
    op.drop_index(op.f('ix_pdme_ano'), table_name='pe_de_meia_etapa')
    op.drop_index(op.f('ix_pdme_etapa_ensino'), table_name='pe_de_meia_etapa')
    op.drop_index(op.f('ix_pdme_mes'), table_name='pe_de_meia_etapa')
    op.drop_index(op.f('ix_pdme_municipio_id'), table_name='pe_de_meia_etapa')
    op.drop_index(op.f('ix_pdme_tipo_incentivo'), table_name='pe_de_meia_etapa')
    op.create_index(op.f('ix_pe_de_meia_etapa_ano'), 'pe_de_meia_etapa', ['ano'], unique=False)
    op.create_index(op.f('ix_pe_de_meia_etapa_etapa_ensino'), 'pe_de_meia_etapa', ['etapa_ensino'], unique=False)
    op.create_index(op.f('ix_pe_de_meia_etapa_id'), 'pe_de_meia_etapa', ['id'], unique=False)
    op.create_index(op.f('ix_pe_de_meia_etapa_mes'), 'pe_de_meia_etapa', ['mes'], unique=False)
    op.create_index(op.f('ix_pe_de_meia_etapa_municipio_id'), 'pe_de_meia_etapa', ['municipio_id'], unique=False)
    op.create_index(op.f('ix_pe_de_meia_etapa_tipo_incentivo'), 'pe_de_meia_etapa', ['tipo_incentivo'], unique=False)
    op.drop_index(op.f('ix_pdm_ano'), table_name='pe_de_meia_resumo')
    op.drop_index(op.f('ix_pdm_mes'), table_name='pe_de_meia_resumo')
    op.drop_index(op.f('ix_pdm_municipio_id'), table_name='pe_de_meia_resumo')
    op.create_index(op.f('ix_pe_de_meia_resumo_ano'), 'pe_de_meia_resumo', ['ano'], unique=False)
    op.create_index(op.f('ix_pe_de_meia_resumo_id'), 'pe_de_meia_resumo', ['id'], unique=False)
    op.create_index(op.f('ix_pe_de_meia_resumo_mes'), 'pe_de_meia_resumo', ['mes'], unique=False)
    op.create_index(op.f('ix_pe_de_meia_resumo_municipio_id'), 'pe_de_meia_resumo', ['municipio_id'], unique=False)
    op.alter_column('pib_anual', 'tipo_dado',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('pib_anual', 'pib_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.create_index(op.f('ix_pib_anual_ano'), 'pib_anual', ['ano'], unique=False)
    op.create_index(op.f('ix_pib_anual_id'), 'pib_anual', ['id'], unique=False)
    op.create_index(op.f('ix_pib_anual_municipio_id'), 'pib_anual', ['municipio_id'], unique=False)
    op.alter_column('pix_mensal', 'ano',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pix_mensal', 'mes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('plano_gov_acoes', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('plano_gov_acoes', 'criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('plano_gov_acoes', 'atualizado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('projeto_eixos', 'ordem',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('projeto_eixos', 'criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('projeto_templates', 'criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('projeto_templates', 'atualizado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('projetos', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('projetos', 'criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('projetos', 'atualizado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('projetos_eixo_id_fkey'), 'projetos', type_='foreignkey')
    op.create_foreign_key(None, 'projetos', 'projeto_eixos', ['eixo_id'], ['id'])
    op.alter_column('rais_metricas_anuais', 'ano',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_rais_cnae_ano'), table_name='rais_por_cnae')
    op.drop_index(op.f('ix_rais_cnae_municipio_id'), table_name='rais_por_cnae')
    op.create_index(op.f('ix_rais_por_cnae_ano'), 'rais_por_cnae', ['ano'], unique=False)
    op.create_index(op.f('ix_rais_por_cnae_id'), 'rais_por_cnae', ['id'], unique=False)
    op.create_index(op.f('ix_rais_por_cnae_municipio_id'), 'rais_por_cnae', ['municipio_id'], unique=False)
    op.alter_column('rais_por_escolaridade', 'ano',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('rais_por_faixa_etaria', 'ano',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('rais_por_faixa_remuneracao', 'ano',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('rais_por_faixa_tempo_emprego', 'ano',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_rais_raca_ano'), table_name='rais_por_raca')
    op.drop_index(op.f('ix_rais_raca_municipio_id'), table_name='rais_por_raca')
    op.create_index(op.f('ix_rais_por_raca_ano'), 'rais_por_raca', ['ano'], unique=False)
    op.create_index(op.f('ix_rais_por_raca_id'), 'rais_por_raca', ['id'], unique=False)
    op.create_index(op.f('ix_rais_por_raca_municipio_id'), 'rais_por_raca', ['municipio_id'], unique=False)
    op.drop_index(op.f('ix_rais_sexo_ano'), table_name='rais_por_sexo')
    op.drop_index(op.f('ix_rais_sexo_municipio_id'), table_name='rais_por_sexo')
    op.create_index(op.f('ix_rais_por_sexo_ano'), 'rais_por_sexo', ['ano'], unique=False)
    op.create_index(op.f('ix_rais_por_sexo_id'), 'rais_por_sexo', ['id'], unique=False)
    op.create_index(op.f('ix_rais_por_sexo_municipio_id'), 'rais_por_sexo', ['municipio_id'], unique=False)
    op.drop_index(op.f('ix_rais_ano'), table_name='rais_vinculos')
    op.drop_index(op.f('ix_rais_municipio_id'), table_name='rais_vinculos')
    op.create_index(op.f('ix_rais_vinculos_ano'), 'rais_vinculos', ['ano'], unique=False)
    op.create_index(op.f('ix_rais_vinculos_id'), 'rais_vinculos', ['id'], unique=False)
    op.create_index(op.f('ix_rais_vinculos_municipio_id'), 'rais_vinculos', ['municipio_id'], unique=False)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.drop_constraint(op.f('usuarios_email_key'), 'usuarios', type_='unique')
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.create_unique_constraint(op.f('usuarios_email_key'), 'usuarios', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_index(op.f('ix_rais_vinculos_municipio_id'), table_name='rais_vinculos')
    op.drop_index(op.f('ix_rais_vinculos_id'), table_name='rais_vinculos')
    op.drop_index(op.f('ix_rais_vinculos_ano'), table_name='rais_vinculos')
    op.create_index(op.f('ix_rais_municipio_id'), 'rais_vinculos', ['municipio_id'], unique=False)
    op.create_index(op.f('ix_rais_ano'), 'rais_vinculos', ['ano'], unique=False)
    op.drop_index(op.f('ix_rais_por_sexo_municipio_id'), table_name='rais_por_sexo')
    op.drop_index(op.f('ix_rais_por_sexo_id'), table_name='rais_por_sexo')
    op.drop_index(op.f('ix_rais_por_sexo_ano'), table_name='rais_por_sexo')
    op.create_index(op.f('ix_rais_sexo_municipio_id'), 'rais_por_sexo', ['municipio_id'], unique=False)
    op.create_index(op.f('ix_rais_sexo_ano'), 'rais_por_sexo', ['ano'], unique=False)
    op.drop_index(op.f('ix_rais_por_raca_municipio_id'), table_name='rais_por_raca')
    op.drop_index(op.f('ix_rais_por_raca_id'), table_name='rais_por_raca')
    op.drop_index(op.f('ix_rais_por_raca_ano'), table_name='rais_por_raca')
    op.create_index(op.f('ix_rais_raca_municipio_id'), 'rais_por_raca', ['municipio_id'], unique=False)
    op.create_index(op.f('ix_rais_raca_ano'), 'rais_por_raca', ['ano'], unique=False)
    op.alter_column('rais_por_faixa_tempo_emprego', 'ano',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('rais_por_faixa_remuneracao', 'ano',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('rais_por_faixa_etaria', 'ano',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('rais_por_escolaridade', 'ano',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_rais_por_cnae_municipio_id'), table_name='rais_por_cnae')
    op.drop_index(op.f('ix_rais_por_cnae_id'), table_name='rais_por_cnae')
    op.drop_index(op.f('ix_rais_por_cnae_ano'), table_name='rais_por_cnae')
    op.create_index(op.f('ix_rais_cnae_municipio_id'), 'rais_por_cnae', ['municipio_id'], unique=False)
    op.create_index(op.f('ix_rais_cnae_ano'), 'rais_por_cnae', ['ano'], unique=False)
    op.alter_column('rais_metricas_anuais', 'ano',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'projetos', type_='foreignkey')
    op.create_foreign_key(op.f('projetos_eixo_id_fkey'), 'projetos', 'projeto_eixos', ['eixo_id'], ['id'], ondelete='CASCADE')
    op.alter_column('projetos', 'atualizado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('projetos', 'criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('projetos', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('projeto_templates', 'atualizado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('projeto_templates', 'criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('projeto_eixos', 'criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('projeto_eixos', 'ordem',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('plano_gov_acoes', 'atualizado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('plano_gov_acoes', 'criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('plano_gov_acoes', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('pix_mensal', 'mes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pix_mensal', 'ano',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_pib_anual_municipio_id'), table_name='pib_anual')
    op.drop_index(op.f('ix_pib_anual_id'), table_name='pib_anual')
    op.drop_index(op.f('ix_pib_anual_ano'), table_name='pib_anual')
    op.alter_column('pib_anual', 'pib_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('pib_anual', 'tipo_dado',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_index(op.f('ix_pe_de_meia_resumo_municipio_id'), table_name='pe_de_meia_resumo')
    op.drop_index(op.f('ix_pe_de_meia_resumo_mes'), table_name='pe_de_meia_resumo')
    op.drop_index(op.f('ix_pe_de_meia_resumo_id'), table_name='pe_de_meia_resumo')
    op.drop_index(op.f('ix_pe_de_meia_resumo_ano'), table_name='pe_de_meia_resumo')
    op.create_index(op.f('ix_pdm_municipio_id'), 'pe_de_meia_resumo', ['municipio_id'], unique=False)
    op.create_index(op.f('ix_pdm_mes'), 'pe_de_meia_resumo', ['mes'], unique=False)
    op.create_index(op.f('ix_pdm_ano'), 'pe_de_meia_resumo', ['ano'], unique=False)
    op.drop_index(op.f('ix_pe_de_meia_etapa_tipo_incentivo'), table_name='pe_de_meia_etapa')
    op.drop_index(op.f('ix_pe_de_meia_etapa_municipio_id'), table_name='pe_de_meia_etapa')
    op.drop_index(op.f('ix_pe_de_meia_etapa_mes'), table_name='pe_de_meia_etapa')
    op.drop_index(op.f('ix_pe_de_meia_etapa_id'), table_name='pe_de_meia_etapa')
    op.drop_index(op.f('ix_pe_de_meia_etapa_etapa_ensino'), table_name='pe_de_meia_etapa')
    op.drop_index(op.f('ix_pe_de_meia_etapa_ano'), table_name='pe_de_meia_etapa')
    op.create_index(op.f('ix_pdme_tipo_incentivo'), 'pe_de_meia_etapa', ['tipo_incentivo'], unique=False)
    op.create_index(op.f('ix_pdme_municipio_id'), 'pe_de_meia_etapa', ['municipio_id'], unique=False)
    op.create_index(op.f('ix_pdme_mes'), 'pe_de_meia_etapa', ['mes'], unique=False)
    op.create_index(op.f('ix_pdme_etapa_ensino'), 'pe_de_meia_etapa', ['etapa_ensino'], unique=False)
    op.create_index(op.f('ix_pdme_ano'), 'pe_de_meia_etapa', ['ano'], unique=False)
    op.drop_index(op.f('ix_municipios_id'), table_name='municipios')
    op.drop_index(op.f('ix_marcos_mandato_id'), table_name='marcos_mandato')
    op.drop_index(op.f('ix_inss_anual_municipio_id'), table_name='inss_anual')
    op.drop_index(op.f('ix_inss_anual_id'), table_name='inss_anual')
    op.drop_index(op.f('ix_inss_anual_categoria'), table_name='inss_anual')
    op.drop_index(op.f('ix_inss_anual_ano'), table_name='inss_anual')
    op.create_index(op.f('ix_inss_municipio_id'), 'inss_anual', ['municipio_id'], unique=False)
    op.create_index(op.f('ix_inss_categoria'), 'inss_anual', ['categoria'], unique=False)
    op.create_index(op.f('ix_inss_ano'), 'inss_anual', ['ano'], unique=False)
    op.drop_index(op.f('ix_insights_ia_id'), table_name='insights_ia')
    op.alter_column('insights_ia', 'gerado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('indicadores_internos', 'criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('eventos_municipio', 'criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_estban_por_instituicao_nome_instituicao'), table_name='estban_por_instituicao')
    op.drop_index(op.f('ix_estban_por_instituicao_municipio_id'), table_name='estban_por_instituicao')
    op.drop_index(op.f('ix_estban_por_instituicao_id'), table_name='estban_por_instituicao')
    op.drop_index(op.f('ix_estban_por_instituicao_data_referencia'), table_name='estban_por_instituicao')
    op.create_index(op.f('ix_estban_inst_nome'), 'estban_por_instituicao', ['nome_instituicao'], unique=False)
    op.create_index(op.f('ix_estban_inst_municipio_id'), 'estban_por_instituicao', ['municipio_id'], unique=False)
    op.create_index(op.f('ix_estban_inst_data_ref'), 'estban_por_instituicao', ['data_referencia'], unique=False)
    op.drop_index(op.f('ix_estban_mensal_municipio_id'), table_name='estban_mensal')
    op.drop_index(op.f('ix_estban_mensal_id'), table_name='estban_mensal')
    op.drop_index(op.f('ix_estban_mensal_data_referencia'), table_name='estban_mensal')
    op.create_index(op.f('ix_estban_municipio_id'), 'estban_mensal', ['municipio_id'], unique=False)
    op.create_index(op.f('ix_estban_data_ref'), 'estban_mensal', ['data_referencia'], unique=False)
    op.drop_index(op.f('ix_empresas_id'), table_name='empresas')
    op.alter_column('dataset_info', 'atualizado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_comex_por_produto_tipo_operacao'), table_name='comex_por_produto')
    op.drop_index(op.f('ix_comex_por_produto_municipio_id'), table_name='comex_por_produto')
    op.drop_index(op.f('ix_comex_por_produto_id'), table_name='comex_por_produto')
    op.drop_index(op.f('ix_comex_por_produto_ano'), table_name='comex_por_produto')
    op.create_index(op.f('ix_comex_prod_tipo_op'), 'comex_por_produto', ['tipo_operacao'], unique=False)
    op.create_index(op.f('ix_comex_prod_municipio_id'), 'comex_por_produto', ['municipio_id'], unique=False)
    op.create_index(op.f('ix_comex_prod_ano'), 'comex_por_produto', ['ano'], unique=False)
    op.drop_index(op.f('ix_comex_por_pais_tipo_operacao'), table_name='comex_por_pais')
    op.drop_index(op.f('ix_comex_por_pais_municipio_id'), table_name='comex_por_pais')
    op.drop_index(op.f('ix_comex_por_pais_id'), table_name='comex_por_pais')
    op.drop_index(op.f('ix_comex_por_pais_ano'), table_name='comex_por_pais')
    op.create_index(op.f('ix_comex_pais_tipo_op'), 'comex_por_pais', ['tipo_operacao'], unique=False)
    op.create_index(op.f('ix_comex_pais_municipio_id'), 'comex_por_pais', ['municipio_id'], unique=False)
    op.create_index(op.f('ix_comex_pais_ano'), 'comex_por_pais', ['ano'], unique=False)
    op.drop_index(op.f('ix_comex_mensal_tipo_operacao'), table_name='comex_mensal')
    op.drop_index(op.f('ix_comex_mensal_municipio_id'), table_name='comex_mensal')
    op.drop_index(op.f('ix_comex_mensal_mes'), table_name='comex_mensal')
    op.drop_index(op.f('ix_comex_mensal_id'), table_name='comex_mensal')
    op.drop_index(op.f('ix_comex_mensal_ano'), table_name='comex_mensal')
    op.create_index(op.f('ix_comex_tipo_op'), 'comex_mensal', ['tipo_operacao'], unique=False)
    op.create_index(op.f('ix_comex_municipio_id'), 'comex_mensal', ['municipio_id'], unique=False)
    op.create_index(op.f('ix_comex_mes'), 'comex_mensal', ['mes'], unique=False)
    op.create_index(op.f('ix_comex_ano'), 'comex_mensal', ['ano'], unique=False)
    op.drop_index(op.f('ix_caged_salario_id'), table_name='caged_salario')
    op.drop_index(op.f('ix_caged_por_sexo_municipio_id'), table_name='caged_por_sexo')
    op.drop_index(op.f('ix_caged_por_sexo_mes'), table_name='caged_por_sexo')
    op.drop_index(op.f('ix_caged_por_sexo_id'), table_name='caged_por_sexo')
    op.drop_index(op.f('ix_caged_por_sexo_ano'), table_name='caged_por_sexo')
    op.create_index(op.f('ix_caged_sexo_municipio_id'), 'caged_por_sexo', ['municipio_id'], unique=False)
    op.create_index(op.f('ix_caged_sexo_mes'), 'caged_por_sexo', ['mes'], unique=False)
    op.create_index(op.f('ix_caged_sexo_ano'), 'caged_por_sexo', ['ano'], unique=False)
    op.drop_index(op.f('ix_caged_por_raca_municipio_id'), table_name='caged_por_raca')
    op.drop_index(op.f('ix_caged_por_raca_mes'), table_name='caged_por_raca')
    op.drop_index(op.f('ix_caged_por_raca_id'), table_name='caged_por_raca')
    op.drop_index(op.f('ix_caged_por_raca_ano'), table_name='caged_por_raca')
    op.create_index(op.f('ix_caged_raca_municipio_id'), 'caged_por_raca', ['municipio_id'], unique=False)
    op.create_index(op.f('ix_caged_raca_mes'), 'caged_por_raca', ['mes'], unique=False)
    op.create_index(op.f('ix_caged_raca_ano'), 'caged_por_raca', ['ano'], unique=False)
    op.drop_index(op.f('ix_caged_por_cnae_municipio_id'), table_name='caged_por_cnae')
    op.drop_index(op.f('ix_caged_por_cnae_mes'), table_name='caged_por_cnae')
    op.drop_index(op.f('ix_caged_por_cnae_id'), table_name='caged_por_cnae')
    op.drop_index(op.f('ix_caged_por_cnae_ano'), table_name='caged_por_cnae')
    op.create_index(op.f('ix_caged_cnae_municipio_id'), 'caged_por_cnae', ['municipio_id'], unique=False)
    op.create_index(op.f('ix_caged_cnae_mes'), 'caged_por_cnae', ['mes'], unique=False)
    op.create_index(op.f('ix_caged_cnae_ano'), 'caged_por_cnae', ['ano'], unique=False)
    op.drop_index(op.f('ix_caged_movimentacao_municipio_id'), table_name='caged_movimentacao')
    op.drop_index(op.f('ix_caged_movimentacao_mes'), table_name='caged_movimentacao')
    op.drop_index(op.f('ix_caged_movimentacao_id'), table_name='caged_movimentacao')
    op.drop_index(op.f('ix_caged_movimentacao_ano'), table_name='caged_movimentacao')
    op.create_index(op.f('ix_caged_municipio_id'), 'caged_movimentacao', ['municipio_id'], unique=False)
    op.create_index(op.f('ix_caged_mes'), 'caged_movimentacao', ['mes'], unique=False)
    op.create_index(op.f('ix_caged_ano'), 'caged_movimentacao', ['ano'], unique=False)
    op.drop_index(op.f('ix_bolsa_familia_resumo_municipio_id'), table_name='bolsa_familia_resumo')
    op.drop_index(op.f('ix_bolsa_familia_resumo_mes'), table_name='bolsa_familia_resumo')
    op.drop_index(op.f('ix_bolsa_familia_resumo_id'), table_name='bolsa_familia_resumo')
    op.drop_index(op.f('ix_bolsa_familia_resumo_ano'), table_name='bolsa_familia_resumo')
    op.create_index(op.f('ix_bf_municipio_id'), 'bolsa_familia_resumo', ['municipio_id'], unique=False)
    op.create_index(op.f('ix_bf_mes'), 'bolsa_familia_resumo', ['mes'], unique=False)
    op.create_index(op.f('ix_bf_ano'), 'bolsa_familia_resumo', ['ano'], unique=False)
    op.drop_index(op.f('ix_arrecadacao_mensal_municipio_id'), table_name='arrecadacao_mensal')
    op.drop_index(op.f('ix_arrecadacao_mensal_mes'), table_name='arrecadacao_mensal')
    op.drop_index(op.f('ix_arrecadacao_mensal_id'), table_name='arrecadacao_mensal')
    op.drop_index(op.f('ix_arrecadacao_mensal_ano'), table_name='arrecadacao_mensal')
    op.alter_column('arrecadacao_mensal', 'valor_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('arrecadacao_mensal', 'valor_ipi',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('arrecadacao_mensal', 'valor_ipva',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('arrecadacao_mensal', 'valor_icms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('arrecadacao_mensal', 'data_base',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('arrecadacao_mensal', 'nome_mes',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_index(op.f('ix_visita_retencao_municipio_id'), table_name='visita_retencao')
    op.drop_index(op.f('ix_visita_retencao_id'), table_name='visita_retencao')
    op.drop_index(op.f('ix_visita_retencao_empresa_id'), table_name='visita_retencao')
    op.drop_table('visita_retencao')
    op.drop_index(op.f('ix_escrita_projeto_oportunidade_captacao_id'), table_name='escrita_projeto')
    op.drop_index(op.f('ix_escrita_projeto_municipio_id'), table_name='escrita_projeto')
    op.drop_index(op.f('ix_escrita_projeto_id'), table_name='escrita_projeto')
    op.drop_table('escrita_projeto')
    op.drop_index(op.f('ix_premiacao_municipio_id'), table_name='premiacao')
    op.drop_index(op.f('ix_premiacao_id'), table_name='premiacao')
    op.drop_table('premiacao')
    op.drop_index(op.f('ix_investimento_funil_municipio_id'), table_name='investimento_funil')
    op.drop_index(op.f('ix_investimento_funil_id'), table_name='investimento_funil')
    op.drop_table('investimento_funil')
    op.drop_index(op.f('ix_empresa_retencao_municipio_id'), table_name='empresa_retencao')
    op.drop_index(op.f('ix_empresa_retencao_id'), table_name='empresa_retencao')
    op.drop_table('empresa_retencao')
    op.drop_index(op.f('ix_captacao_recurso_municipio_id'), table_name='captacao_recurso')
    op.drop_index(op.f('ix_captacao_recurso_id'), table_name='captacao_recurso')
    op.drop_table('captacao_recurso')
    # ### end Alembic commands ###
