"""add caged escolaridade faixa_etaria tipo_movimentacao tables

Revision ID: b002efc404da
Revises: 68bbe475530f
Create Date: 2026-05-07 10:27:30.143552

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'b002efc404da'
down_revision = '68bbe475530f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caged_por_escolaridade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipio_id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('grau_instrucao', sa.String(length=80), nullable=False),
    sa.Column('admissoes', sa.Integer(), nullable=False),
    sa.Column('desligamentos', sa.Integer(), nullable=False),
    sa.Column('saldo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caged_por_escolaridade_ano'), 'caged_por_escolaridade', ['ano'], unique=False)
    op.create_index(op.f('ix_caged_por_escolaridade_id'), 'caged_por_escolaridade', ['id'], unique=False)
    op.create_index(op.f('ix_caged_por_escolaridade_mes'), 'caged_por_escolaridade', ['mes'], unique=False)
    op.create_index(op.f('ix_caged_por_escolaridade_municipio_id'), 'caged_por_escolaridade', ['municipio_id'], unique=False)
    op.create_table('caged_por_faixa_etaria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipio_id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('faixa_etaria', sa.String(length=30), nullable=False),
    sa.Column('admissoes', sa.Integer(), nullable=False),
    sa.Column('desligamentos', sa.Integer(), nullable=False),
    sa.Column('saldo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caged_por_faixa_etaria_ano'), 'caged_por_faixa_etaria', ['ano'], unique=False)
    op.create_index(op.f('ix_caged_por_faixa_etaria_id'), 'caged_por_faixa_etaria', ['id'], unique=False)
    op.create_index(op.f('ix_caged_por_faixa_etaria_mes'), 'caged_por_faixa_etaria', ['mes'], unique=False)
    op.create_index(op.f('ix_caged_por_faixa_etaria_municipio_id'), 'caged_por_faixa_etaria', ['municipio_id'], unique=False)
    op.create_table('caged_por_tipo_movimentacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipio_id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('tipo_movimentacao', sa.String(length=80), nullable=False),
    sa.Column('admissoes', sa.Integer(), nullable=False),
    sa.Column('desligamentos', sa.Integer(), nullable=False),
    sa.Column('saldo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caged_por_tipo_movimentacao_ano'), 'caged_por_tipo_movimentacao', ['ano'], unique=False)
    op.create_index(op.f('ix_caged_por_tipo_movimentacao_id'), 'caged_por_tipo_movimentacao', ['id'], unique=False)
    op.create_index(op.f('ix_caged_por_tipo_movimentacao_mes'), 'caged_por_tipo_movimentacao', ['mes'], unique=False)
    op.create_index(op.f('ix_caged_por_tipo_movimentacao_municipio_id'), 'caged_por_tipo_movimentacao', ['municipio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_caged_por_tipo_movimentacao_municipio_id'), table_name='caged_por_tipo_movimentacao')
    op.drop_index(op.f('ix_caged_por_tipo_movimentacao_mes'), table_name='caged_por_tipo_movimentacao')
    op.drop_index(op.f('ix_caged_por_tipo_movimentacao_id'), table_name='caged_por_tipo_movimentacao')
    op.drop_index(op.f('ix_caged_por_tipo_movimentacao_ano'), table_name='caged_por_tipo_movimentacao')
    op.drop_table('caged_por_tipo_movimentacao')
    op.drop_index(op.f('ix_caged_por_faixa_etaria_municipio_id'), table_name='caged_por_faixa_etaria')
    op.drop_index(op.f('ix_caged_por_faixa_etaria_mes'), table_name='caged_por_faixa_etaria')
    op.drop_index(op.f('ix_caged_por_faixa_etaria_id'), table_name='caged_por_faixa_etaria')
    op.drop_index(op.f('ix_caged_por_faixa_etaria_ano'), table_name='caged_por_faixa_etaria')
    op.drop_table('caged_por_faixa_etaria')
    op.drop_index(op.f('ix_caged_por_escolaridade_municipio_id'), table_name='caged_por_escolaridade')
    op.drop_index(op.f('ix_caged_por_escolaridade_mes'), table_name='caged_por_escolaridade')
    op.drop_index(op.f('ix_caged_por_escolaridade_id'), table_name='caged_por_escolaridade')
    op.drop_index(op.f('ix_caged_por_escolaridade_ano'), table_name='caged_por_escolaridade')
    op.drop_table('caged_por_escolaridade')
    # ### end Alembic commands ###
