// Fonte única de verdade das chaves de indicador_info (KPIs e gráficos).
// Consumida pelas páginas (via literais idênticos) e pela tela /admin/indicadores.
// Convenção: gráficos usam prefixo chart_; KPIs mantêm as chaves históricas.
// Teste de paridade em indicadorCatalog.test.js garante JSX ⊆ catálogo.

export const INDICADOR_CATALOG = {
  geral: [
    { key: "chart_evolucao_pib", label: "Evolução do PIB", tipo: "chart" },
    { key: "chart_receita_por_tipo", label: "Receita por Tipo", tipo: "chart" },
    { key: "chart_va_setor", label: "Valor Adicionado por Setor", tipo: "chart" },
    { key: "chart_pib_comparativo", label: "PIB Comparativo", tipo: "chart" },
    { key: "chart_saldo_caged", label: "Saldo CAGED", tipo: "chart" },
    { key: "chart_top_setores_va", label: "Top Setores · VA", tipo: "chart" },
  ],
  arrecadacao: [
    { key: "total_arrecadado", label: "Total Arrecadado", tipo: "kpi" },
    { key: "ultimo_ano", label: "Último Ano", tipo: "kpi" },
    { key: "media_mensal", label: "Média Mensal", tipo: "kpi" },
    { key: "crescimento_anual", label: "Crescimento", tipo: "kpi" },
    { key: "chart_serie_mensal", label: "Série Histórica Mensal", tipo: "chart" },
    { key: "chart_composicao_tipo", label: "Composição por Tipo de Imposto", tipo: "chart" },
    { key: "chart_detalhamento_periodo", label: "Detalhamento por Período", tipo: "chart" },
  ],
  pib: [
    { key: "ultimo_ano", label: "PIB — Último Ano", tipo: "kpi" },
    { key: "crescimento", label: "Crescimento", tipo: "kpi" },
    { key: "anos_serie", label: "Anos na Série", tipo: "kpi" },
    { key: "chart_evolucao_anual", label: "Evolução Anual do PIB", tipo: "chart" },
    { key: "chart_va_setor", label: "Valor Adicionado por Setor", tipo: "chart" },
    { key: "chart_pib_comparativo", label: "PIB Comparativo — Municípios", tipo: "chart" },
    { key: "chart_serie_anual", label: "Série Anual", tipo: "chart" },
    { key: "chart_comparativo_municipios", label: "Comparativo com Municípios", tipo: "chart" },
  ],
  vaf: [
    { key: "ipm_ultimo_ano", label: "IPM — Último Ano-Base", tipo: "kpi" },
    { key: "variacao_ipm", label: "Variação do IPM", tipo: "kpi" },
    { key: "anos_serie", label: "Anos na Série", tipo: "kpi" },
    { key: "chart_evolucao_ipm", label: "Evolução do IPM", tipo: "chart" },
    { key: "chart_icms_projetado", label: "ICMS Projetado a partir do IPM", tipo: "chart" },
    { key: "chart_indice_vs_medio", label: "Índice vs Índice Médio", tipo: "chart" },
    { key: "chart_ipm_comparativo", label: "IPM Comparativo — Municípios", tipo: "chart" },
    { key: "chart_vaf_individual_estado", label: "VAF Individual × Estado", tipo: "chart" },
    { key: "chart_serie_anual", label: "Série Anual", tipo: "chart" },
    { key: "chart_comparativo_municipios", label: "Comparativo com Municípios", tipo: "chart" },
  ],
  fpm: [
    { key: "fpm_12m", label: "FPM Últimos 12 Meses", tipo: "kpi" },
    { key: "coeficiente", label: "Coeficiente Estimado", tipo: "kpi" },
    { key: "valor_por_ponto", label: "Valor por Ponto de Coeficiente", tipo: "kpi" },
    { key: "populacao", label: "População", tipo: "kpi" },
    { key: "chart_repasses_mensais", label: "Repasses Mensais do FPM", tipo: "chart" },
    { key: "chart_populacao_anual", label: "População Estimada por Ano", tipo: "chart" },
    { key: "chart_total_anual", label: "Total Anual", tipo: "chart" },
  ],
  captacao_federal: [
    { key: "voce_firmado", label: "Captação Firmada", tipo: "kpi" },
    { key: "via_emenda", label: "Via Emenda Parlamentar", tipo: "kpi" },
    { key: "desembolsado", label: "Desembolsado", tipo: "kpi" },
    { key: "posicao", label: "Posição no Grupo", tipo: "kpi" },
    { key: "chart_captacao_anual", label: "Captação Anual — Você vs Pares", tipo: "chart" },
    { key: "chart_detalhe_anual", label: "Detalhe Anual", tipo: "chart" },
  ],
  emendas: [
    { key: "total_empenhado", label: "Total Destinado (Empenhado)", tipo: "kpi" },
    { key: "pago_total", label: "Executado (Pago)", tipo: "kpi" },
    { key: "num_parlamentares", label: "Parlamentares", tipo: "kpi" },
    { key: "top_autor", label: "Maior Padrinho", tipo: "kpi" },
    { key: "chart_ranking_parlamentar", label: "Ranking por Parlamentar", tipo: "chart" },
    { key: "chart_destino_area", label: "Destino por Área", tipo: "chart" },
    { key: "chart_funil_execucao", label: "Emendas — Funil de Execução", tipo: "chart" },
  ],
  caged: [
    { key: "kpi_saldo_acumulado", label: "Saldo · Acumulado", tipo: "kpi" },
    { key: "kpi_admissoes", label: "Admissões", tipo: "kpi" },
    { key: "kpi_desligamentos", label: "Desligamentos", tipo: "kpi" },
    { key: "kpi_salario_medio_admissao", label: "Salário Médio · Admissão", tipo: "kpi" },
    { key: "kpi_trabalho_parcial", label: "Trabalho Parcial", tipo: "kpi" },
    { key: "kpi_intermitente", label: "Intermitente", tipo: "kpi" },
    { key: "kpi_aprendizes", label: "Aprendizes", tipo: "kpi" },
    { key: "kpi_pcd", label: "PCD", tipo: "kpi" },
    { key: "chart_saldo", label: "Saldo Mensal/Anual", tipo: "chart" },
    { key: "chart_movimentacao", label: "Movimentação CAGED", tipo: "chart" },
    { key: "chart_setores_saldo", label: "Setores · Saldo do Ano", tipo: "chart" },
    { key: "chart_composicao_setorial", label: "Composição Setorial", tipo: "chart" },
    { key: "chart_tamanho_estabelecimento", label: "Por Tamanho de Estabelecimento", tipo: "chart" },
    { key: "chart_pcd_deficiencia", label: "PCD por Tipo de Deficiência", tipo: "chart" },
    { key: "chart_tipo_empregador", label: "Tipo de Empregador", tipo: "chart" },
    { key: "chart_tipo_estabelecimento", label: "Tipo de Estabelecimento", tipo: "chart" },
    { key: "chart_setores_historico", label: "Movimentações por Setor · Histórico", tipo: "chart" },
    { key: "chart_admissoes_sexo", label: "Admissões por Sexo", tipo: "chart" },
    { key: "chart_admissoes_raca", label: "Admissões por Raça/Cor", tipo: "chart" },
    { key: "chart_admissoes_faixa_etaria", label: "Admissões por Faixa Etária", tipo: "chart" },
    { key: "chart_admissoes_escolaridade", label: "Admissões por Escolaridade", tipo: "chart" },
    { key: "chart_tipo_movimentacao", label: "Tipo de Movimentação", tipo: "chart" },
  ],
  rais: [
    { key: "kpi_total_vinculos", label: "Total de Vínculos", tipo: "kpi" },
    { key: "kpi_ativos_31_12", label: "Ativos em 31/12", tipo: "kpi" },
    { key: "kpi_remuneracao_media", label: "Remuneração Média", tipo: "kpi" },
    { key: "kpi_pcd", label: "PCD (Pessoas com Deficiência)", tipo: "kpi" },
    { key: "kpi_trabalho_parcial", label: "Trabalho Parcial", tipo: "kpi" },
    { key: "kpi_intermitente", label: "Intermitente", tipo: "kpi" },
    { key: "kpi_empresa_simples", label: "Empresa do Simples", tipo: "kpi" },
    { key: "kpi_aprendizes", label: "Aprendizes (estim.)", tipo: "kpi" },
    { key: "chart_evolucao_vinculos", label: "Evolução de Vínculos", tipo: "chart" },
    { key: "chart_top_setores", label: "Top Setores (CNAE)", tipo: "chart" },
    { key: "chart_turnover_mensal", label: "Turnover Mensal", tipo: "chart" },
    { key: "chart_natureza_juridica", label: "Natureza Jurídica", tipo: "chart" },
    { key: "chart_tipo_admissao", label: "Tipo de Admissão", tipo: "chart" },
    { key: "chart_tamanho_estabelecimento", label: "Por Tamanho de Estabelecimento", tipo: "chart" },
    { key: "chart_evolucao_setor", label: "Evolução por Setor", tipo: "chart" },
    { key: "chart_vinculos_sexo", label: "Vínculos por Sexo", tipo: "chart" },
    { key: "chart_vinculos_raca", label: "Vínculos por Raça/Cor", tipo: "chart" },
    { key: "chart_faixa_etaria", label: "Faixa Etária", tipo: "chart" },
    { key: "chart_grau_instrucao", label: "Grau de Instrução", tipo: "chart" },
    { key: "chart_faixa_salarial", label: "Faixa Salarial (Salários Mínimos)", tipo: "chart" },
    { key: "chart_tempo_emprego", label: "Tempo de Emprego", tipo: "chart" },
    { key: "chart_motivos_desligamento", label: "Motivos de Desligamento", tipo: "chart" },
    { key: "chart_top_ocupacoes", label: "Top 10 Ocupações (CBO 2002)", tipo: "chart" },
  ],
  bolsa_familia: [
    { key: "total_beneficiarios", label: "Total de Beneficiários", tipo: "kpi" },
    { key: "valor_total", label: "Valor Total", tipo: "kpi" },
    { key: "media_por_beneficiario", label: "Média por Beneficiário", tipo: "kpi" },
    { key: "chart_evolucao_beneficiarios", label: "Evolução de Beneficiários", tipo: "chart" },
    { key: "chart_total_vs_primeira_infancia", label: "Beneficiários: Total vs Primeira Infância", tipo: "chart" },
    { key: "chart_repasses", label: "Repasses: Bolsa Família vs Primeira Infância", tipo: "chart" },
    { key: "chart_comparativo_municipios", label: "Comparativo com Municípios", tipo: "chart" },
  ],
  pe_de_meia: [
    { key: "total_estudantes", label: "Total de Estudantes", tipo: "kpi" },
    { key: "valor_total", label: "Valor Total", tipo: "kpi" },
    { key: "chart_evolucao_estudantes", label: "Evolução de Estudantes Beneficiados", tipo: "chart" },
    { key: "chart_por_etapa", label: "Estudantes por Etapa de Ensino", tipo: "chart" },
    { key: "chart_por_incentivo", label: "Estudantes por Tipo de Incentivo", tipo: "chart" },
  ],
  inss: [
    { key: "total_beneficios", label: "Total de Benefícios", tipo: "kpi" },
    { key: "valor_total", label: "Valor Total", tipo: "kpi" },
    { key: "chart_top_categorias", label: "Top Categorias de Benefícios", tipo: "chart" },
    { key: "chart_evolucao_anual", label: "Evolução Anual de Benefícios", tipo: "chart" },
    { key: "chart_detalhamento_ano_categoria", label: "Detalhamento por Ano e Categoria", tipo: "chart" },
    { key: "chart_comparativo_municipios", label: "Comparativo com Municípios", tipo: "chart" },
  ],
  ips: [
    { key: "ips_geral", label: "IPS Geral", tipo: "kpi" },
    { key: "ranking_nacional", label: "Ranking Nacional", tipo: "kpi" },
    { key: "ranking_estadual", label: "Ranking Estadual", tipo: "kpi" },
    { key: "pib_per_capita", label: "PIB per Capita", tipo: "kpi" },
    { key: "necessidades_humanas_basicas", label: "Necessidades Humanas Básicas", tipo: "kpi" },
    { key: "fundamentos_bem_estar", label: "Fundamentos do Bem-estar", tipo: "kpi" },
    { key: "oportunidades", label: "Oportunidades", tipo: "kpi" },
    { key: "chart_perfil_componente", label: "Perfil por Componente", tipo: "chart" },
    { key: "chart_pontos_fortes", label: "Pontos Fortes", tipo: "chart" },
    { key: "chart_pontos_melhorar", label: "Pontos a Melhorar", tipo: "chart" },
    { key: "chart_evolucao_tempo", label: "Evolução ao Longo do Tempo", tipo: "chart" },
    { key: "chart_comparar_municipios", label: "Comparar com Outros Municípios", tipo: "chart" },
  ],
  estban: [
    { key: "agencias", label: "Agências", tipo: "kpi" },
    { key: "credito_total", label: "Crédito Total", tipo: "kpi" },
    { key: "depositos_total", label: "Depósitos Totais", tipo: "kpi" },
    { key: "chart_evolucao_credito", label: "Evolução das Operações de Crédito", tipo: "chart" },
    { key: "chart_captacao_depositos", label: "Evolução da Captação — Depósitos por Tipo", tipo: "chart" },
    { key: "chart_credito_vs_captacao", label: "Crédito vs Captação Total", tipo: "chart" },
    { key: "chart_composicao_credito", label: "Composição das Operações de Crédito", tipo: "chart" },
    { key: "chart_credito_instituicao", label: "Operações de Crédito por Instituição", tipo: "chart" },
    { key: "chart_composicao_credito_instituicao", label: "Composição do Crédito por Instituição", tipo: "chart" },
    { key: "chart_detalhamento_instituicao", label: "Detalhamento por Instituição", tipo: "chart" },
    { key: "chart_comparativo_municipios", label: "Comparativo com Municípios", tipo: "chart" },
  ],
  comex: [
    { key: "exportacoes", label: "Exportações", tipo: "kpi" },
    { key: "importacoes", label: "Importações", tipo: "kpi" },
    { key: "saldo", label: "Saldo", tipo: "kpi" },
    { key: "chart_exp_vs_imp", label: "Exportações vs Importações", tipo: "chart" },
    { key: "chart_saldo_mensal", label: "Saldo da Balança Comercial (Mensal)", tipo: "chart" },
    { key: "chart_volume_fisico", label: "Volume Físico — Peso Exportado vs Importado", tipo: "chart" },
    { key: "chart_top_produtos", label: "Top 10 Produtos", tipo: "chart" },
    { key: "chart_top_produtos_peso", label: "Top Produtos por Peso", tipo: "chart" },
    { key: "chart_top_paises", label: "Top 10 Países", tipo: "chart" },
    { key: "chart_comparativo_municipios", label: "Comparativo com Municípios", tipo: "chart" },
  ],
  empresas: [
    { key: "abertas_periodo", label: "Abertas no Período", tipo: "kpi" },
    { key: "total_empresas", label: "Total de Empresas", tipo: "kpi" },
    { key: "ativas", label: "Ativas", tipo: "kpi" },
    { key: "mei", label: "MEI", tipo: "kpi" },
    { key: "simples", label: "Simples Nacional", tipo: "kpi" },
    { key: "chart_porte", label: "Distribuição por Porte", tipo: "chart" },
    { key: "chart_situacao_cadastral", label: "Empresas por Situação Cadastral", tipo: "chart" },
    { key: "chart_ativas_fechadas_porte", label: "Ativas vs Fechadas por Porte", tipo: "chart" },
    { key: "chart_setor_cnae", label: "Empresas por Setor de Atividade (CNAE)", tipo: "chart" },
    { key: "chart_capital_social_porte", label: "Capital Social por Porte de Empresa", tipo: "chart" },
  ],
  pix: [
    { key: "volume_pf", label: "Volume PF", tipo: "kpi" },
    { key: "volume_pj", label: "Volume PJ", tipo: "kpi" },
    { key: "volume_total", label: "Volume Total", tipo: "kpi" },
    { key: "chart_vol_pagamentos", label: "Volume de Pagamentos — PF vs PJ", tipo: "chart" },
    { key: "chart_vol_recebimentos", label: "Volume de Recebimentos — PF vs PJ", tipo: "chart" },
    { key: "chart_qtd_transacoes", label: "Quantidade de Transações (Pagadores)", tipo: "chart" },
    { key: "chart_pagadores_unicos", label: "Pessoas Únicas Pagadoras", tipo: "chart" },
    { key: "chart_recebedores_unicos", label: "Pessoas Únicas Recebedoras", tipo: "chart" },
    { key: "chart_comparativo_municipios", label: "Comparativo com Municípios", tipo: "chart" },
  ],
};

export function todasAsChaves() {
  const s = new Set();
  for (const entries of Object.values(INDICADOR_CATALOG)) {
    for (const e of entries) s.add(e.key);
  }
  return s;
}
