"""Divisão CNAE (2 primeiros dígitos do cnae_fiscal) → descrição da seção.
Compartilhado por /empresas/por_cnae_secao e pela descoberta na base RFB."""

# CNAE division (2 digits) → section description
CNAE_SECAO = {
    "01": "Agricultura, pecuária e produção florestal", "02": "Agricultura, pecuária e produção florestal",
    "03": "Pesca e aquicultura",
    "05": "Extração de carvão mineral", "06": "Extração de petróleo e gás natural",
    "07": "Extração de minerais metálicos", "08": "Extração de minerais não metálicos",
    "09": "Atividades de apoio à extração de minerais",
    "10": "Fabricação de produtos alimentícios", "11": "Fabricação de bebidas",
    "12": "Fabricação de produtos do fumo", "13": "Fabricação de produtos têxteis",
    "14": "Confecção de artigos do vestuário", "15": "Fabricação de calçados e artefatos de couro",
    "16": "Fabricação de produtos de madeira", "17": "Fabricação de celulose e papel",
    "18": "Impressão e reprodução", "19": "Fabricação de coque e derivados de petróleo",
    "20": "Fabricação de produtos químicos", "21": "Fabricação de produtos farmoquímicos",
    "22": "Fabricação de produtos de borracha e plástico", "23": "Fabricação de minerais não metálicos",
    "24": "Metalurgia", "25": "Fabricação de produtos de metal",
    "26": "Fabricação de equipamentos de informática e eletrônicos",
    "27": "Fabricação de máquinas e equipamentos elétricos",
    "28": "Fabricação de máquinas e equipamentos",
    "29": "Fabricação de veículos automotores", "30": "Fabricação de outros equipamentos de transporte",
    "31": "Fabricação de móveis", "32": "Fabricação de produtos diversos",
    "33": "Manutenção e reparação de máquinas",
    "35": "Eletricidade e gás", "36": "Captação e distribuição de água",
    "37": "Esgoto e atividades relacionadas", "38": "Coleta e tratamento de resíduos",
    "39": "Descontaminação e outros serviços",
    "41": "Construção de edifícios", "42": "Obras de infraestrutura",
    "43": "Serviços especializados para construção",
    "45": "Comércio e reparação de veículos automotores",
    "46": "Comércio por atacado", "47": "Comércio varejista",
    "49": "Transporte terrestre", "50": "Transporte aquaviário",
    "51": "Transporte aéreo", "52": "Armazenamento e atividades auxiliares",
    "53": "Correio e outras atividades de entrega",
    "55": "Alojamento", "56": "Alimentação",
    "58": "Edição", "59": "Atividades cinematográficas e musicais",
    "60": "Atividades de rádio e televisão", "61": "Telecomunicações",
    "62": "Atividades de TI e informática", "63": "Prestação de serviços de informação",
    "64": "Atividades de serviços financeiros", "65": "Seguros e previdência",
    "66": "Atividades auxiliares dos serviços financeiros",
    "68": "Atividades imobiliárias",
    "69": "Atividades jurídicas e contábeis", "70": "Atividades das sedes de empresas",
    "71": "Arquitetura e engenharia", "72": "Pesquisa e desenvolvimento",
    "73": "Publicidade e pesquisa de mercado", "74": "Outras atividades profissionais",
    "75": "Atividades veterinárias",
    "77": "Aluguéis e gestão de bens", "78": "Seleção e agenciamento de mão-de-obra",
    "79": "Agências de viagem", "80": "Atividades de vigilância e segurança",
    "81": "Serviços para edifícios e paisagismo", "82": "Serviços de escritório e apoio",
    "84": "Administração pública e seguridade social",
    "85": "Educação",
    "86": "Atividades de atenção à saúde humana", "87": "Atividades de atenção residencial",
    "88": "Serviços sociais sem alojamento",
    "90": "Atividades artísticas, criativas e de espetáculos",
    "91": "Atividades de bibliotecas, arquivos e museus",
    "92": "Atividades de jogos de azar", "93": "Atividades esportivas e de lazer",
    "94": "Atividades de organizações associativas",
    "95": "Reparação de computadores e objetos pessoais",
    "96": "Outras atividades de serviços pessoais",
    "97": "Serviços domésticos",
    "99": "Organismos internacionais",
}
